#!/bin/bash
# Postman Quick Setup Script

echo "==================================="
echo "Postman Testing Quick Reference"
echo "==================================="
echo ""
echo "✅ Server Status: Running on http://localhost:3000"
echo ""
echo "📋 Collection File:"
echo "   Location: Secure-Token-Auth-API.postman_collection.json"
echo ""
echo "📥 Import Steps:"
echo "   1. Open Postman"
echo "   2. Click 'Import' (top-left)"
echo "   3. Select 'File' tab"
echo "   4. Choose: Secure-Token-Auth-API.postman_collection.json"
echo "   5. Click 'Open' then 'Import'"
echo ""
echo "🔑 Environment Setup:"
echo "   1. Create new environment: 'Development'"
echo "   2. Add variable 'token' (keep empty initially)"
echo "   3. Select environment from top-right dropdown"
echo ""
echo "🚀 Testing Flow:"
echo "   1. Health Check → GET /"
echo "   2. Register User → POST /api/auth/register"
echo "   3. Login → POST /api/auth/login (copy token)"
echo "   4. Save token to environment variable"
echo "   5. Validate Token → GET /api/auth/validate"
echo "   6. Get Profile → GET /api/auth/profile"
echo ""
echo "❌ Test Error Cases:"
echo "   • Missing email → 400 Bad Request"
echo "   • Missing password → 400 Bad Request" 
echo "   • Invalid route → 404 Not Found"
echo ""
echo "📊 Collection Structure:"
echo "   ├── Health & Status (2 requests)"
echo "   ├── Authentication (5 requests)"
echo "   └── Error Cases (4 requests)"
echo ""
echo "⏱️  Server Running Time: Check terminal"
echo ""
echo "==================================="
